export const DAILY_GOAL_MINUTES = 200;

export const EFFICIENCY_THRESHOLDS = {
  STUCK: 0.3,
  DEEP: 0.7,
  OPTIMAL_MAX: 1.3,
  SPEED: 1.7,
  ALARM_THRESHOLD: 2.5,
} as const;

export const EFFICIENCY_CONFIG = {
  DAILY_GOAL_MINUTES,
  THRESHOLDS: EFFICIENCY_THRESHOLDS,
} as const;
