export const MOCK_QUIZ_QUESTIONS = [
  {
    idx: 0,
    id: 'a5c8b9ae-01a2-4e03-8882-fa52a058fa1b',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '414025c0-4c3e-4a28-93aa-2ff9f25b21b5',
    section_title: 'Finansal Matematik',
    question_data: JSON.stringify({
      a: 1,
      o: [
        '$A = 12.100$ TL',
        '$A = 12.160$ TL',
        '$A = 12.240$ TL',
        '$A = 12.320$ TL',
        '$A = 12.080$ TL',
      ],
      q: 'Ali, $P=12.000$ TL tutarındaki anaparayı yıllık %8 basit faiz oranı ($r=0,08$) ile yatırmaktadır. Faiz formülü $i = \\frac{I}{P \\cdot t}$ olduğuna ve vade sonunda elde ettiği faiz geliri $I=160$ TL olduğuna göre, vade sonundaki toplam tutarı ($A$) bulunuz.',
      exp: 'Toplam tutar ($A$), ana para ($P$) ve faiz gelirinin ($I$) toplamı ile hesaplanır:\n\n$$A = P + I$$\n\nHesaplama:\n$$A = 12.000 + 160 = 12.160 \\text{ TL}$$',
      img: null,
      evidence:
        'Basit faiz formülü: $I = P \\cdot r \\cdot t$ ve $A = P + I$ eşitlikleri temeldir.',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 14:28:36.802443+00',
    usage_type: 'arsiv',
    bloom_level: 'knowledge',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Basit Faiz ve Toplam Tutar',
  },
  {
    idx: 1,
    id: 'b1e2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '525136d1-5d4f-5b39-0abb-3gg0g6c7h8i9',
    section_title: 'Finansal Analiz',
    question_data: JSON.stringify({
      a: 2,
      o: [
        '$\\text{Cari Oran} > 2$',
        '$\\text{Asit-Test} = 1.0$',
        '$\\text{Borç/Özkaynak} = 1.5$',
        '$\\text{Nakit Oran} = 0.2$',
        '$\\text{ROE} = 0.15$',
      ],
      q: "Bir işletmenin toplam borçları $150.000$ TL ve özkaynakları $100.000$ TL'dir. Bu işletmenin finansal kaldıraç oranını (Borç/Özkaynak) hesaplayınız.",
      exp: 'Borç/Özkaynak oranı, bir işletmenin finansal riskini ölçer:\n\n$$\\text{Borç/Özkaynak Oranı} = \\frac{\\text{Toplam Borç}}{\\text{Toplam Özkaynak}}$$\n\n$$\\frac{150.000}{100.000} = 1.5$$',
      img: null,
      evidence:
        'Finansal analiz standartlarında kaldıraç oranı olarak sınıflandırılır.',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 14:30:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'application',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Finansal Kaldıraç',
  },
  {
    idx: 2,
    id: 'c1d2e3f4-g5h6-7i8j-9k0l-1m2n3o4p5q6r',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '636247e2-6e5g-6c4a-1bcc-4hh1h7d8i9j0',
    section_title: 'Hukukun Temel Kavramları',
    question_data: JSON.stringify({
      a: 0,
      o: [
        'Hukuki Fiil',
        'Hukuki Olay',
        'Hukuki İşlem',
        'Hukuki Aykırılık',
        'Mücbir Sebep',
      ],
      q: 'Hukuki bir sonuç doğurmaya yönelik irade açıklamasına ne ad verilir?\n\nA) Hukuki İşlem\nB) Hukuki Olay\nC) Hukuki Fiil\nD) Hukuki Aykırılık\nE) Mücbir Sebep',
      exp: 'Hukuki işlem, bir veya birden fazla kişinin hukuki bir sonuç doğurmaya yönelik irade beyanıdır. Sözleşmeler buna en iyi örnektir.',
      img: null,
      evidence:
        'Türk Medeni Kanunu ve Borçlar Kanunu öğretisinde temel bir tanımdır.',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 14:35:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'knowledge',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Hukuki İşlemler',
  },
  {
    idx: 3,
    id: 'd1e2f3g4-h5i6-j7k8-l9m0-n1o2p3q4r5s6',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '747358f3-7f6h-7d5b-2cdd-5ii2i8e9j0k1',
    section_title: 'Muhasebe Standartları',
    question_data: JSON.stringify({
      a: 3,
      o: [
        'Dönemsellik Kavramı',
        'İhtiyatlılık Kavramı',
        'Tam Açıklama Kavramı',
        'Özün Önceliği Kavramı',
        'Maliyet Esası Kavramı',
      ],
      q: 'İşlemlerin muhasebeye kaydedilmesinde ve mali tabloların hazırlanmasında biçimden çok, işlemin gerçek mahiyetinin (ekonomik içeriğinin) esas alınması gerektiğini ifade eden kavram hangisidir?\n\nA) Dönemsellik Kavramı\nB) İhtiyatlılık Kavramı\nC) Tam Açıklama Kavramı\nD) Özün Önceliği Kavramı\nE) Maliyet Esası Kavramı',
      exp: 'Özün önceliği kavramı, işlemlerin hukuki biçimlerinden ziyade ekonomik özlerinin raporlanmasını gerektirir.',
      img: null,
      evidence: 'Muhasebenin Temel Kavramları arasında yer alır (TMS/TFRS).',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 14:40:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'analysis',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Muhasebenin Temel Kavramları',
  },
  {
    idx: 4,
    id: 'e1f2g3h4-i5j6-k7l8-m9n0-o1p2q3r4s5t6',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '858469g4-8g7i-8e6c-3dee-6jj3j9f0k1l2',
    section_title: 'İstatistik ve Olasılık',
    question_data: JSON.stringify({
      a: 4,
      o: ['Aritmetik Ortalama', 'Mod', 'Medyan', 'Varyans', 'Standart Sapma'],
      q: 'Veri setindeki değerlerin ortalamadan ne kadar uzaklaştığının bir ölçüsü olan ve varyansın karekökü ile hesaplanan değer hangisidir?\n\nA) Aritmetik Ortalama\nB) Mod\nC) Medyan\nD) Varyans\nE) Standart Sapma',
      exp: 'Standart sapma, verilerin yayılımını ölçen en yaygın istatistiksel araçtır. Varyansın kareköküdür.',
      img: null,
      evidence: 'Tanım gereği standart sapma = √Varyans.',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 14:45:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'application',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Yayılım Ölçüleri',
  },
  {
    idx: 5,
    id: 'f1g2h3i4-j5k6-l7m8-n9o0-p1q2r3s4t5u6',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '969570h5-9h8j-9f7d-4eff-7kk4k0g1l2m3',
    section_title: 'Yönetim Bilimi',
    question_data: JSON.stringify({
      a: 1,
      o: ['Planlama', 'Organizasyon', 'Yöneltme', 'Denetim', 'Eşgüdüm'],
      q: 'Yönetim süreçlerinden hangisi, belirlenen hedeflere ulaşılıp ulaşılmadığını kontrol etme ve gerekiyorsa düzeltici faaliyetleri yürütme aşamasıdır?\n\nA) Planlama\nB) Denetim\nC) Organizasyon\nD) Yöneltme\nE) Eşgüdüm',
      exp: 'Denetim (kontrol), planlanan sonuçlar ile gerçekleşen sonuçların karşılaştırılması ve sapmaların tespit edilmesidir.',
      img: null,
      evidence: "Fayol'un yönetim fonksiyonlarından biridir.",
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 14:50:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'knowledge',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Yönetim Fonksiyonları',
  },
  {
    idx: 6,
    id: 'g1h2i3j4-k5l6-m7n8-o9p0-q1r2s3t4u5v6',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '070681i6-0i9k-0g8e-5fgg-8ll5l1h2m3n4',
    section_title: 'Pazarlama İlkeleri',
    question_data: JSON.stringify({
      a: 2,
      o: [
        'Segmentasyon',
        'Konumlandırma',
        'Pazarlama Karması (4P)',
        'SWOT Analizi',
        'Misyon Belirleme',
      ],
      q: 'Ürün, Fiyat, Dağıtım ve Tutundurma bileşenlerinden oluşan stratejik bütüne ne ad verilir?\n\nA) Segmentasyon\nB) Konumlandırma\nC) Pazarlama Karması (4P)\nD) SWOT Analizi\nE) Misyon Belirleme',
      exp: 'Pazarlama Karması (Marketing Mix), bir işletmenin pazar hedeflerine ulaşmak için kullandığı kontrol edilebilir araçların birleşimidir (Product, Price, Place, Promotion).',
      img: null,
      evidence: "McCarthy tarafından 1960'ta popüler hale getirilmiştir.",
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 14:55:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'knowledge',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Pazarlama Karması',
  },
  {
    idx: 7,
    id: 'h1i2j3k4-l5m6-n7o8-p9q0-r1s2t3u4v5w6',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '181792j7-1j0l-1h9f-6ghh-9mm6m2i3n4o5',
    section_title: 'Banka Hukuku',
    question_data: JSON.stringify({
      a: 3,
      o: [
        'Ticaret Bakanlığı',
        'Hazine ve Maliye Bakanlığı',
        'Merkez Bankası',
        'BDDK',
        'TMSF',
      ],
      q: "Türkiye'de bankaların kuruluş ve faaliyet izinlerini verme, düzenleme ve denetleme yetkisine sahip kurum hangisidir?\n\nA) Ticaret Bakanlığı\nB) Merkez Bankası\nC) Hazine ve Maliye Bakanlığı\nD) BDDK\nE) TMSF",
      exp: 'Bankacılık Düzenleme ve Denetleme Kurumu (BDDK), finansal piyasaların güven ve istikrar içinde çalışmasını sağlamakla görevlidir.',
      img: null,
      evidence: '5411 sayılı Bankacılık Kanunu uyarınca yetkilidir.',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 15:00:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'knowledge',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Denetleyici Kurumlar',
  },
  {
    idx: 8,
    id: 'i1j2k3l4-m5n6-o7p8-q9r0-s1t2u3v4w5x6',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '292803k8-2k1m-2i0g-7hii-0nn7n3j4o5p6',
    section_title: 'Denetim Teknikleri',
    question_data: JSON.stringify({
      a: 0,
      o: [
        'Doğrulama (Konfirmasyon)',
        'Gözlem',
        'İnceleme',
        'Yeniden Hesaplama',
        'Analitik Prosedürler',
      ],
      q: 'Denetçinin, bir bilgiyi veya var olan bir durumu üçüncü bir şahıstan doğrudan yazılı olarak teyit etmesi işlemine ne ad verilir?\n\nA) Doğrulama (Konfirmasyon)\nB) Gözlem\nC) İnceleme\nD) Yeniden Hesaplama\nE) Analitik Prosedürler',
      exp: 'Doğrulama, denetim kanıtı toplama tekniklerinden biridir. Özellikle banka bakiyeleri ve alacaklar için kullanılır.',
      img: null,
      evidence:
        'Uluslararası Denetim Standartları (ISA 505) kapsamında tanımlanmıştır.',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 15:05:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'application',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Denetim Kanıtı Toplama',
  },
  {
    idx: 9,
    id: 'j1k2l3m4-n5o6-p7q8-r9s0-t1u2v3w4x5y6',
    course_id: 'e1cba265-9465-44ab-8b74-ba208ab7fc9a',
    chunk_id: '303914l9-3l2n-3j1h-8ijj-1oo8o4k5p6q7',
    section_title: 'Genel Ekonomi',
    question_data: JSON.stringify({
      a: 4,
      o: ['Deflasyon', 'Stagflasyon', 'Devalüasyon', 'Resesyon', 'Enflasyon'],
      q: 'Fiyatlar genel düzeyinin sürekli ve hissedilir bir şekilde artması durumuna ne ad verilir?\n\nA) Deflasyon\nB) Stagflasyon\nC) Devalüasyon\nD) Resesyon\nE) Enflasyon',
      exp: 'Enflasyon, paranın satın alma gücünün azalması ve yaşam maliyetinin artmasıdır.',
      img: null,
      evidence: 'Makro ekonominin temel kavramlarından biridir.',
    }),
    created_by: 'f63e5a09-7401-481d-9cfb-c1bb1940a999',
    created_at: '2026-02-16 15:10:00.000000+00',
    usage_type: 'arsiv',
    bloom_level: 'knowledge',
    parent_question_id: null,
    evidence: null,
    concept_title: 'Fiyat İstikrarı',
  },
];
