import DOMPurify from 'dompurify';

export type ContentType = 'strict' | 'markdown' | 'raw' | 'html';

export const STRICT_CONFIG = {
  USE_PROFILES: { html: false },
  ALLOWED_TAGS: [] as string[],
  ALLOWED_ATTR: [] as string[],
  KEEP_CONTENT: true,
  FORBID_TAGS: ['script', 'style', 'iframe', 'form', 'object', 'embed', 'link'],
  FORBID_ATTR: [
    'onerror',
    'onload',
    'onclick',
    'onmouseover',
    'onmouseout',
    'onmousedown',
    'onmouseup',
    'onmousemove',
    'onkeypress',
    'onkeydown',
    'onkeyup',
    'onfocus',
    'onblur',
    'onchange',
    'onsubmit',
    'onreset',
    'onselect',
  ],
};

export const MARKDOWN_CONFIG = {
  ALLOWED_TAGS: [
    'b',
    'strong',
    'i',
    'em',
    'u',
    'mark',
    'small',
    'del',
    'ins',
    'sub',
    'sup',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'ul',
    'ol',
    'li',
    'dl',
    'dt',
    'dd',
    'a',
    'code',
    'pre',
    'kbd',
    'samp',
    'table',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'td',
    'th',
    'caption',
    'colgroup',
    'col',
    'blockquote',
    'p',
    'br',
    'hr',
    'div',
    'span',
    'img',
    'figure',
    'figcaption',
    'details',
    'summary',
    'svg',
    'path',
    'rect',
    'circle',
    'line',
    'polyline',
    'polygon',
    'text',
    'g',
    'defs',
    'marker',
    'use',
    'foreignObject',
  ],
  ALLOWED_ATTR: [
    'class',
    'id',
    'title',
    'dir',
    'lang',
    'role',
    'aria-label',
    'aria-hidden',
    'href',
    'target',
    'rel',
    'src',
    'alt',
    'width',
    'height',
    'loading',
    'colspan',
    'rowspan',
    'scope',
    'data-language',
    'viewBox',
    'd',
    'fill',
    'stroke',
    'stroke-width',
    'transform',
    'cx',
    'cy',
    'r',
    'x',
    'y',
    'points',
    'marker-end',
    'marker-start',
    'xmlns',
    'xmlns:xlink',
    'preserveAspectRatio',
  ],
  FORBID_TAGS: [
    'script',
    'style',
    'iframe',
    'form',
    'object',
    'embed',
    'link',
    'meta',
    'head',
  ],
  FORBID_ATTR: [
    'onerror',
    'onload',
    'onclick',
    'onmouseover',
    'onmouseout',
    'onmousedown',
    'onmouseup',
    'onmousemove',
    'onkeypress',
    'onkeydown',
    'onkeyup',
    'onfocus',
    'onblur',
    'onchange',
    'onsubmit',
    'onreset',
    'onselect',
  ],
  ALLOW_DATA_ATTR: false,
  SANITIZE_DOM: true,
  ALLOWED_URI_REGEXP:
    /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp|xxx):|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i,
};

export const HTML_CONFIG = {
  USE_PROFILES: { html: true, svg: true, mathMl: true },
  ADD_TAGS: [
    'use',
    'foreignObject',
    'div',
    'span',
    'br',
    'p',
    'math',
    'semantics',
    'annotation',
    'mrow',
    'msup',
    'msub',
    'msubsup',
    'mover',
    'munder',
    'munderover',
    'mfrac',
    'msqrt',
    'mroot',
    'mi',
    'mo',
    'mn',
  ],
  ADD_ATTR: [
    'cx',
    'cy',
    'r',
    'fill',
    'stroke',
    'stroke-width',
    'd',
    'points',
    'viewBox',
    'width',
    'height',
    'x',
    'y',
    'role',
    'aria-hidden',
    'id',
    'class',
    'transform',
    'style',
    'xlink:href',
    'preserveAspectRatio',
    'vector-effect',
    'marker-end',
    'marker-start',
    'marker-mid',
  ],
  FORBID_TAGS: [
    'script',
    'style',
    'iframe',
    'form',
    'input',
    'textarea',
    'object',
    'embed',
    'link',
  ],
  FORBID_ATTR: [
    'onerror',
    'onload',
    'onclick',
    'onmouseover',
    'onmouseout',
    'onmousedown',
    'onmouseup',
    'onmousemove',
    'onkeypress',
    'onkeydown',
    'onkeyup',
    'onfocus',
    'onblur',
    'onchange',
    'onsubmit',
    'onreset',
    'onselect',
    'onabort',
    'onunload',
    'onbeforeunload',
    'onresize',
    'onscroll',
  ],
};

export function sanitizeString(
  value: string,
  contentType: ContentType = 'strict'
): string {
  if (typeof value !== 'string') return value;
  if (contentType === 'raw') return value;

  const config =
    contentType === 'markdown'
      ? MARKDOWN_CONFIG
      : contentType === 'html'
        ? HTML_CONFIG
        : STRICT_CONFIG;
  return DOMPurify.sanitize(value, config);
}

export const sanitizeHtml = (html: string): string =>
  sanitizeString(html, 'html');
