import { type QuizQuestion } from '@/features/quiz/types';

export const MOCK_QUESTIONS: QuizQuestion[] = [
  {
    id: 'mock-1',
    type: 'multiple_choice',
    q: "Para talebinin faiz esnekliğinin sonsuz ($e_{mi} = \\infty$) olduğu bir 'Likidite Tuzağı' ortamında, otonom kamu harcamalarının ($G$) artırılmasının hasıla ($Y$) üzerindeki etkisi nedir?",
    o: [
      "LM eğrisi yatay olduğu için 'tam dışlama' yaratır; hasıla değişmez.",
      'Para arzı artışı faizi düşüremeyeceği için maliye politikası etkisizdir.',
      'IS eğrisi sağa kayar, faizler değişmez ve hasıla maksimum çarpan etkisiyle artar.',
      'Yatırımın faiz esnekliği sıfır olduğu için sadece para politikası etkilidir.',
      'Fiyatlar genel düzeyi düşer ve ekonomi kendiliğinden tam istihdama döner.',
    ],
    a: 2,
    exp: 'Likidite tuzağında LM eğrisi yataydır (faiz esnekliği sonsuzdur). Bu durumda genişlemeci bir maliye politikası ($G \\uparrow$) IS eğrisini sağa kaydırdığında, faiz oranlarında herhangi bir yükselme meydana gelmez. Faizler artmadığı için özel yatırımların azalması (Dışlama Etkisi) sıfıra iner ve maliye politikası en yüksek etkinlik düzeyine ulaşır.',
    evidence: 'Makro İktisat Teorisi',
  },
  {
    id: 'mock-2',
    type: 'multiple_choice',
    q: "Bir yatırımcı, 5 yıl boyunca her 3 ayda bir dönem sonlarında $20.000$ TL'yi yıllık %16 nominal faizle fon hesabına yatıracaktır. Gelecek değer hesabı için gerekli olan efektif dönem faizi ($i$) ve toplam dönem sayısı ($n$) nedir?",
    o: [
      '$i=0.16; n=5$',
      '$i=0.04; n=5$',
      '$i=0.04; n=20$',
      '$i=0.0133; n=60$',
      '$i=0.16; n=20$',
    ],
    a: 2,
    exp: 'Üçer aylık periyotlar için yıllık nominal faiz (%16) dörde bölünmelidir: $16 / 4 = 4$ yani $i=0.04$. Toplam dönem sayısı ise yıl sayısı ile yıldaki periyot sayısının çarpımıdır: $5 \\times 4 = 20$. Formül: $FV = A \\times \\frac{(1+i)^n - 1}{i}$.',
    evidence: 'Finans Matematiği',
  },
  {
    id: 'mock-3',
    type: 'multiple_choice',
    q: '3 yıl kıdemi olan İşçi (A), performans düşüklüğü gerekçe gösterilerek savunması alınmaksızın ve ihbar tazminatı peşin ödenerek işten çıkarılmıştır. İş yerinde $50$ işçi çalışmaktadır. Bu vaka uyarınca, 4857 Sayılı İş Kanunu kapsamında izlenmesi gereken hukuki yol nedir?',
    o: [
      'Fesih haklı nedenle yapıldığı için işçi hiçbir tazminata veya işe iade davasına hak kazanamaz.',
      'Savunma alınmadığı için fesih doğrudan geçersizdir; işçi doğrudan İş Mahkemesinde dava açmalıdır.',
      'İşçi kıdem tazminatını aldığı için feshi kabul etmiş sayılır ve sadece arabulucuya başvurabilir.',
      'Savunma alınmaması feshin usulden geçersizliğine yol açar; işçi zorunlu arabuluculuk sürecinin ardından işe iade davası açabilir.',
      'İşçi $6$ aylık kıdem şartını sağlamasına rağmen ihbar tazminatı ödendiği için iş güvencesi hükümlerinden yararlanamaz.',
    ],
    a: 3,
    exp: "İş Kanunu m.19 uyarınca, işçinin davranışı veya verimiyle ilgili nedenlerle yapılan fesihlerde, işçinin savunmasının alınması bir geçerlilik şartıdır. Savunma alınmaması feshin usulden geçersizliği sonucunu doğurur. Ayrıca, 7036 Sayılı Kanun gereği işe iade talebiyle açılacak davalarda arabuluculuğa başvurulması bir 'dava şartı'dır.",
    evidence: 'İş Hukuku m.19',
  },
  {
    id: 'mock-4',
    type: 'multiple_choice',
    q: "(A), lehine düzenlenmiş $100.000$ TL değerindeki bir bonoyu imzalayarak (B)’ye teslim etmiş; (B) ise hiçbir ibare yazmadan senedi (C)’ye devretmiştir. Düzenleyen (D), (C)'nin isminin zincirde geçmediğini belirterek ödemeden kaçınmıştır. Hukuki durum nedir?",
    o: [
      'Ciro zinciri (B)’nin isminin yazılmaması nedeniyle kopmuştur; (C) meşru hamil sayılmaz.',
      "(A)’nın yaptığı işlem 'Tam Ciro', (B)’nih yaptığı işlem 'Beyaz Ciro'dur; zincir kopmamıştır.",
      '(A) beyaz ciro yapmıştır; beyaz ciro ile alan (B), senedi sadece teslimle (C)’ye devredebilir ve (C) meşru hamil olur.',
      'Bono emre yazılı olduğu için ismen belirtilmeyen devirler geçersizdir.',
      '(C), cirantaların imza geçerliliğini ispat etmekle yükümlüdür.',
    ],
    a: 2,
    exp: 'TTK m.683 uyarınca beyaz ciro (sadece imza), senedi hamiline yazılı senede yaklaştırır. Beyaz ciro ile senedi devralan kişi, ismini yazmadan sadece teslimle senedi başkasına devredebilir. Bu durum TTK m.686 kapsamında ciro zincirini koparmaz.',
    evidence: 'TTK m.683, m.686',
  },
  {
    id: 'mock-5',
    type: 'multiple_choice',
    q: 'Toplam varlıkları $1.000.000$ TL, borç/öz kaynak oranı 1, borç maliyeti %10, vergi oranı %20 ve FVÖK tutarı $200.000$ TL olan bir firmanın Öz Kaynak Karlılığı (ROE) nedir?',
    o: [
      'ROE %15’tir; kaldıraç pozitiftir.',
      'ROE %12’dir; kaldıraç olumludur.',
      'ROE %24’tür; kaldıraç karlılığı artırmıştır.',
      'ROE %10’dur; kaldıraç etkisi nötrdür.',
      'ROE %20’dir; öz kaynak karlılığı faiz öncesidir.',
    ],
    a: 2,
    exp: 'Öz Kaynak = $500.000$ TL, Borç = $500.000$ TL. Faiz Gideri = $500.000 \\times 0.10 = 50.000$ TL. Vergi Öncesi Kâr = $200.000 - 50.000 = 150.000$ TL. Net Kâr = $150.000 \\times 0.80 = 120.000$ TL. $ROE = 120.000 / 500.000 = %24$.',
    evidence: 'Finansal Yönetim - ROE Analizi',
  },
];
