import DOMPurify from 'dompurify';

/**
 * Sanitize HTML/SVG content to prevent XSS attacks.
 * Configured to support Mermaid SVG and KaTeX math formulas.
 */
export const sanitizeHtml = (html: string): string => {
  return DOMPurify.sanitize(html, {
    USE_PROFILES: { html: true, svg: true, mathMl: true },
    ADD_TAGS: [
      'use',
      'foreignObject',
      'div',
      'span',
      'br',
      'p',
      'math',
      'semantics',
      'annotation',
      'mrow',
      'msup',
      'msub',
      'msubsup',
      'mover',
      'munder',
      'munderover',
      'mfrac',
      'msqrt',
      'mroot',
      'mi',
      'mo',
      'mn',
    ],
    ADD_ATTR: [
      'cx',
      'cy',
      'r',
      'fill',
      'stroke',
      'stroke-width',
      'd',
      'points',
      'viewBox',
      'width',
      'height',
      'x',
      'y',
      'role',
      'aria-hidden',
      'id',
      'class',
      'transform',
      'style',
      'xlink:href',
      'preserveAspectRatio',
      'vector-effect',
      'marker-end',
      'marker-start',
      'marker-mid',
    ],
    FORBID_TAGS: [
      'script',
      'style',
      'iframe',
      'form',
      'input',
      'textarea',
      'object',
      'embed',
      'link',
    ],
    FORBID_ATTR: [
      'onerror',
      'onload',
      'onclick',
      'onmouseover',
      'onmouseout',
      'onmousedown',
      'onmouseup',
      'onmousemove',
      'onkeypress',
      'onkeydown',
      'onkeyup',
      'onfocus',
      'onblur',
      'onchange',
      'onsubmit',
      'onreset',
      'onselect',
      'onabort',
      'onunload',
      'onbeforeunload',
      'onresize',
      'onscroll',
    ],
  });
};
