import { type Achievement } from '../types/achievementsTypes';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'hukuk_10',
    title: 'Yasa Tozu',
    motto: 'Kadim tabletlerdeki ilk çatlakları ve tozlu yasaları fark ettin.',
    imagePath: '/badges/hukuk-10.webp',
    guild: 'HUKUK',
    requirement: {
      type: 'category_progress',
      category: 'HUKUK',
      percentage: 10,
    },
    order: 1,
  },
  {
    id: 'hukuk_25',
    title: 'Demir Mühürdar',
    motto: 'Sarsılmaz kuralların anahtarını sıkıca kavrıyorsun.',
    imagePath: '/badges/hukuk-25.webp',
    guild: 'HUKUK',
    requirement: {
      type: 'category_progress',
      category: 'HUKUK',
      percentage: 25,
    },
    order: 2,
  },
  {
    id: 'hukuk_50',
    title: 'Rün Mürekkebi',
    motto:
      'Karmaşık yazıtların arasındaki gizli rünleri deşifre etmeye başladın.',
    imagePath: '/badges/hukuk-50.webp',
    guild: 'HUKUK',
    requirement: {
      type: 'category_progress',
      category: 'HUKUK',
      percentage: 50,
    },
    order: 3,
  },
  {
    id: 'hukuk_100',
    title: 'Adalet Asası',
    motto:
      'Kadim yasaların mutlak koruyucusu; adaletin keskin ve parlayan kılıcı.',
    imagePath: '/badges/hukuk-100.webp',
    guild: 'HUKUK',
    requirement: {
      type: 'category_progress',
      category: 'HUKUK',
      percentage: 100,
    },
    order: 4,
  },
  {
    id: 'eko_10',
    title: 'Bakır Yol',
    motto: 'Ticaret kervanlarının geçtiği tozlu yollarda ilk adımını attın.',
    imagePath: '/badges/ekonomi-10.webp',
    guild: 'EKONOMI',
    requirement: {
      type: 'category_progress',
      category: 'EKONOMI',
      percentage: 10,
    },
    order: 5,
  },
  {
    id: 'eko_25',
    title: 'Kervan Katibi',
    motto: 'Altın sikkelerin sesini ve servetin yönünü anlamaya başladın.',
    imagePath: '/badges/ekonomi-25.webp',
    guild: 'EKONOMI',
    requirement: {
      type: 'category_progress',
      category: 'EKONOMI',
      percentage: 25,
    },
    order: 6,
  },
  {
    id: 'eko_50',
    title: 'Denge Gözetmeni',
    motto:
      'Arz ve talebin fırtınalı denizinde, sükuneti ve düzeni görebiliyorsun.',
    imagePath: '/badges/ekonomi-50.webp',
    guild: 'EKONOMI',
    requirement: {
      type: 'category_progress',
      category: 'EKONOMI',
      percentage: 50,
    },
    order: 7,
  },
  {
    id: 'eko_100',
    title: 'Altın Dokunuş Üstadı',
    motto:
      'Altın akışının sırrına erdin; görünmez eller artık senin iradene boyun eğiyor.',
    imagePath: '/badges/ekonomi-100.webp',
    guild: 'EKONOMI',
    requirement: {
      type: 'category_progress',
      category: 'EKONOMI',
      percentage: 100,
    },
    order: 8,
  },
  {
    id: 'muh_10',
    title: 'Düğüm Çözücü',
    motto: 'Sayıların karmaşık düğümlerini teker teker çözmeye başladın.',
    imagePath: '/badges/muhasebe-10.webp',
    guild: 'MUHASEBE_MALIYE',
    requirement: {
      type: 'category_progress',
      category: 'MUHASEBE_MALIYE',
      percentage: 10,
    },
    order: 9,
  },
  {
    id: 'muh_25',
    title: 'Hazine Muhafızı',
    motto: 'Hazine kapısındaki ağır kilidin mekanizmasını çözüyorsun.',
    imagePath: '/badges/muhasebe-25.webp',
    guild: 'MUHASEBE_MALIYE',
    requirement: {
      type: 'category_progress',
      category: 'MUHASEBE_MALIYE',
      percentage: 25,
    },
    order: 10,
  },
  {
    id: 'muh_50',
    title: 'Gümüş Sayacı',
    motto:
      'Krallığın sandığını koruyan, her sikkenin fısıltısını duyan keskin göz.',
    imagePath: '/badges/muhasebe-50.webp',
    guild: 'MUHASEBE_MALIYE',
    requirement: {
      type: 'category_progress',
      category: 'MUHASEBE_MALIYE',
      percentage: 50,
    },
    order: 11,
  },
  {
    id: 'muh_100',
    title: 'Kusursuz Mizân Üstadı',
    motto: 'Sayıların kaosunu ilahi bir düzene sokan, mutlak dengenin mimarı.',
    imagePath: '/badges/muhasebe-100.webp',
    guild: 'MUHASEBE_MALIYE',
    requirement: {
      type: 'category_progress',
      category: 'MUHASEBE_MALIYE',
      percentage: 100,
    },
    order: 12,
  },
  {
    id: 'genel_10',
    title: 'Yolcu Meşalesi',
    motto: 'Zihnin karanlık koridorlarında ilk meşaleyi sen yaktın.',
    imagePath: '/badges/genel-10.webp',
    guild: 'GENEL_YETENEK',
    requirement: {
      type: 'category_progress',
      category: 'GENEL_YETENEK',
      percentage: 10,
    },
    order: 13,
  },
  {
    id: 'genel_25',
    title: 'Elçi Kuzgunu',
    motto: 'Bilgi uçsuz bucaksız diyarlardan sana doğru kanat çırpıyor.',
    imagePath: '/badges/genel-25.webp',
    guild: 'GENEL_YETENEK',
    requirement: {
      type: 'category_progress',
      category: 'GENEL_YETENEK',
      percentage: 25,
    },
    order: 14,
  },
  {
    id: 'genel_50',
    title: 'Yedi Dilin Elçisi',
    motto: 'Uzak diyarların kadim dillerini konuşan, halklar arasındaki köprü.',
    imagePath: '/badges/genel-50.webp',
    guild: 'GENEL_YETENEK',
    requirement: {
      type: 'category_progress',
      category: 'GENEL_YETENEK',
      percentage: 50,
    },
    order: 15,
  },
  {
    id: 'genel_100',
    title: 'Hakikat Arayıcısı',
    motto:
      'Zihninle en karanlık labirentleri aydınlatan, bilmeceleri parçalayan bilge.',
    imagePath: '/badges/genel-100.webp',
    guild: 'GENEL_YETENEK',
    requirement: {
      type: 'category_progress',
      category: 'GENEL_YETENEK',
      percentage: 100,
    },
    order: 16,
  },
  {
    id: 'hybrid_01',
    title: 'Ticaret Valisi',
    motto:
      'Hukuk ve Ekonomi: Altının akışını yasaların gücüyle dizginliyorsun.',
    imagePath: '/badges/hybrid-01.webp',
    guild: 'HYBRID',
    requirement: {
      type: 'multi_category_progress',
      categories: [
        { category: 'HUKUK', percentage: 25 },
        {
          category: 'EKONOMI',
          percentage: 25,
        },
      ],
    },
    order: 17,
  },
  {
    id: 'hybrid_02',
    title: 'İmparatorluk Nazırı',
    motto: 'Ekonomi ve Muhasebe: Hem serveti yönetiyor hem de tartabiliyorsun.',
    imagePath: '/badges/hybrid-02.webp',
    guild: 'HYBRID',
    requirement: {
      type: 'multi_category_progress',
      categories: [
        { category: 'EKONOMI', percentage: 50 },
        {
          category: 'MUHASEBE_MALIYE',
          percentage: 50,
        },
      ],
    },
    order: 18,
  },
  {
    id: 'hybrid_03',
    title: 'Bilge Diplomat',
    motto: 'Hukuk ve Genel Yetenek: Keskin bir zeka ve sarsılmaz bir adalet.',
    imagePath: '/badges/hybrid-03.webp',
    guild: 'HYBRID',
    requirement: {
      type: 'multi_category_progress',
      categories: [
        { category: 'HUKUK', percentage: 50 },
        {
          category: 'GENEL_YETENEK',
          percentage: 50,
        },
      ],
    },
    order: 19,
  },
  {
    id: 'hybrid_04',
    title: 'Strateji Mimarı',
    motto: 'Muhasebe ve Genel Yetenek: Mantığın ve sayıların gücü.',
    imagePath: '/badges/hybrid-04.webp',
    guild: 'HYBRID',
    requirement: {
      type: 'multi_category_progress',
      categories: [
        { category: 'MUHASEBE_MALIYE', percentage: 25 },
        {
          category: 'GENEL_YETENEK',
          percentage: 25,
        },
      ],
    },
    order: 20,
  },
  {
    id: 'hybrid_05',
    title: 'Büyük Konsey Üyesi',
    motto:
      'Beş disiplin tek zihinde: Tüm loncaların saygısını kazanan bir bilge.',
    imagePath: '/badges/hybrid-05.webp',
    guild: 'HYBRID',
    requirement: { type: 'all_progress', percentage: 50 },
    order: 21,
  },
  {
    id: 'special-01',
    title: 'Gece Nöbetçisi',
    motto: 'Tek bir tefekkür oturumunda tam 5 parşömen bitirdin.',
    imagePath: '/badges/special-01.webp',
    guild: 'SPECIAL',
    requirement: { type: 'daily_progress', count: 5 },
    order: 22,
    isPermanent: true,
  },
  {
    id: 'special-02',
    title: 'Zihinsel Maraton',
    motto: 'Zihnin sınırlarını zorlayan 10 videoluk devasa bir adım.',
    imagePath: '/badges/special-02.webp',
    guild: 'SPECIAL',
    requirement: { type: 'daily_progress', count: 10 },
    order: 23,
    isPermanent: true,
  },
  {
    id: 'special-03',
    title: 'Sönmeyen Meşale',
    motto: 'Yedi gün boyunca karanlığı ilminle dağıttın; meşalen hiç sönmedi.',
    imagePath: '/badges/special-03.webp',
    guild: 'SPECIAL',
    requirement: { type: 'streak', days: 7 },
    order: 24,
    isPermanent: true,
  },
  {
    id: 'special-04',
    title: 'Kutsal Adanmışlık',
    motto: 'Bilgelik yolunda tam bir ay boyunca her gün yürüdün.',
    imagePath: '/badges/special-04.webp',
    guild: 'SPECIAL',
    requirement: { type: 'streak', days: 30 },
    order: 25,
    isPermanent: true,
  },
  {
    id: 'special-05',
    title: 'Zamanın Yolcusu',
    motto:
      'Bilgelik koridorlarında toplam 60 gün geçirdin; artık burası senin evin.',
    imagePath: '/badges/special-05.webp',
    guild: 'SPECIAL',
    requirement: { type: 'total_active_days', days: 60 },
    order: 26,
    isPermanent: true,
  },
  {
    id: 'special-06',
    title: 'Uyanmış Ruh',
    motto:
      'Yolun yarısını aştın; artık tüm disiplinler senin varlığınla uyumlu.',
    imagePath: '/badges/special-06.webp',
    guild: 'SPECIAL',
    requirement: { type: 'all_progress', percentage: 50 },
    order: 27,
  },
  {
    id: 'special-07',
    title: 'Yüce Üstad',
    motto:
      'Tüm mühürler toplandı, tüm isimler öğrenildi. Sen artık yaşayan bir efsanesin.',
    imagePath: '/badges/special-07.webp',
    guild: 'SPECIAL',
    requirement: { type: 'all_progress', percentage: 100 },
    order: 28,
  },
  {
    id: 'RANK_UP:1',
    title: 'Sürgün',
    motto: 'Bilginin krallığından uzakta, sislerin içinde yolunu arıyorsun.',
    imagePath: '/ranks/rank1.webp',
    guild: 'TITLES',
    requirement: { type: 'minimum_videos', count: 1 },
    order: 29,
    isPermanent: true,
  },
  {
    id: 'RANK_UP:2',
    title: 'Yazıcı',
    motto: 'Kadim metinleri kopyalayarak bilgeliğin izlerini sürmeye başladın.',
    imagePath: '/ranks/rank2.webp',
    guild: 'TITLES',
    requirement: { type: 'all_progress', percentage: 25 },
    order: 30,
    isPermanent: true,
  },
  {
    id: 'RANK_UP:3',
    title: 'Sınır Muhafızı',
    motto:
      'Bilgi krallığının sınırlarını koruyor, cehaletin gölgeleriyle savaşıyorsun.',
    imagePath: '/ranks/rank3.webp',
    guild: 'TITLES',
    requirement: { type: 'all_progress', percentage: 50 },
    order: 31,
    isPermanent: true,
  },
  {
    id: 'RANK_UP:4',
    title: 'Yüce Bilgin',
    motto:
      'Görünmeyeni görüyor, bilinmeyeni biliyorsun. Hikmetin ışığı sensin.',
    imagePath: '/ranks/rank4.webp',
    guild: 'TITLES',
    requirement: { type: 'all_progress', percentage: 75 },
    order: 32,
    isPermanent: true,
  },
];
